image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./node_modules/.bin/tsc

test:
  stage: test
  script:
    - ./node_modules/.bin/jest
